version: "3.2"
services:
  rabbit:
    container_name: calendar-rabbitmq
    image: rabbitmq:3.7-management
    ports:
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: "queue_user"
      RABBITMQ_DEFAULT_PASS: "queue-super-password"
    restart: on-failure

  postgres:
    container_name: calendar-postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "event_db"
      POSTGRES_PASSWORD: "event-super-password"
      POSTGRES_USER: "event_user"
    restart: on-failure

  calendar-service:
    container_name: calendar-grpc-server
    build: .
    image: calendar
    depends_on:
      - postgres
      - migrations
    ports:
      - "8080:8080"
    environment:
      GRPC-SRV-HOST: "0.0.0.0"
      GRPC-SRV-PORT: "8080"
      DSN: "host=postgres user=event_user password=event-super-password dbname=event_db"
      STORAGE: "pg"
      VERBOSE: "true"
    command: "/app/calendar gs"

  migrations:
    image: migrate/migrate
    volumes:
      - ./sql/:/migrations
    command: -path /migrations/ -database postgres://event_user:event-super-password@postgres:5432/event_db?sslmode=disable up
    depends_on:
      - postgres