# my global config
global:
  scrape_interval:     15s
  evaluation_interval: 30s
  # scrape_timeout is set to the global default (10s).

  external_labels:
    app: calendar

scrape_configs:
  - job_name: postgres
    metrics_path: /metrics
    static_configs:
      - targets:
          - postgres-exporter:9187
      - labels:
          service: postgres-db
  - job_name: calendar-grpc-server
    metrics_path: /metrics
    static_configs:
      - targets:
          - calendar-service:9001
      - labels:
          service: grpc-server
  - job_name: calendar-sender-service
    metrics_path: /metrics
    static_configs:
      - targets:
          - sender-service:9002
      - labels:
          service: sender
